version: "3.9"
services:
  frontend:
    container_name: http-server
    build:
      context: .
      labels: 
        info.statbot.desc: "StatBot-HTTPServer description"
        info.statbot.title: "StatBot-HTTPServer"
        info.statbot.version: "1"
    ports:
      - 45.153.231.214:443:8080
      - 45.67.230.59:443:8080
    network_mode: bridge
    volumes:
      - type: bind
        source: /var/www/data
        target: /app/static
      - type: volume
        source: certs
        target: /app/certs
      - type: volume
        source: banned
        target: /app/data
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
        delay: 5s
    logging: 
      driver: local
      options: 
        max-size: 200k
        max-file: "10"
volumes: 
  banned:
  certs:
